# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - 2.11.0
  - 2.10.4
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - prasinous@gmail.com
jdk:
  - openjdk7
  - oraclejdk7
services:
  - mongodb
